### ISSUE TITLE
malpem_proot and temp files

### ISSUE THREAD

**Issue by davecash75** [ledigchr/MALPEM#3]
Hi Christian-
When we tried to run MALPEM, we ran into issues that our distributions don't support the tempfile command (line 66), when then caused some problems with the naming structure of the temproary files stored in the $caredir/rootfs/tmp direcotry. Tempfile appears to be deprecated in preference of mktemp, for example see tempfile manual page:
https://www.systutorials.com/docs/linux/man/1-tempfile/

When replaced line 66 using mktemp instead of tempfile, 
`tmpname=`mktemp``
all seems to work now.
Many thanks
David Cash

**Comment by ledigchr** [comment]
Hi David,
Thanks a lot for reporting. As you proposed, replacing ``tempfile`` with ``mktemp`` should fix this. We'll change this in future versions.
Christian

https://github.com/ledigchr/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/bin/malpem-proot#L71

**Comment by ledigchr** [comment]
Addressed in commit 4a9854e3a6593cdd3734eef56375cdd5d38afcc0
