### ISSUE TITLE
Command in CARE environment Error

### ISSUE THREAD

**Issue by uanazodo** [ledigchr/MALPEM#4]
Hello Christian, 

I used malpem version 1.2 with the Ubuntu 14.04 distribution and now have upgraded my desktop and OS to Ubuntu 16.04. I moved the malpem folder to my home directory and tried to run the code but got an error message even when i tried executing the help See below;
-----------------------------------------------------------------------------------------
bin/malpem-proot -h
STATUS: Using libGL library in: /usr/lib/i386-linux-gnu/mesa/libGL.so.1
/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1

Command in CARE environment:
malpem -h

env: ‘/usr/CARElib/x86_64-linux-gnu/mesa:’: No such file or directory
---------------------------------------------------------------------------------------
Any thoughts on how I can fix this. Thanks

**Comment by ledigchr** [comment]
Can you check your `bin/malpem-proot` file and compare to the following line from the repo?
https://github.com/ledigchr/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/bin/malpem-proot#L17

The script shouldn't be able to find the libraries in your error message.

If the above doesn't solve your problem. A quick fix to your problem should be to delete the above line from the script and instead set `myGL = ""`  This fix will however disable offscreen rendering which is only relevant for the pdf report and should be the only limitation of this fix.

**Comment by uanazodo** [comment]
Hello Christian,

I had edited line #17 in the malpem-proot to myGL=`locate 'libGL.so.1' |
egrep '*.so.1$' | egrep ^/usr/lib`

So it can locate the libGL.so.1 file.

which produced the error message I reported.

However when I changed it to myGL= " ". I got the following error message

STATUS: Using libGL library in:
dirname: missing operand
Try 'dirname --help' for more information.

Command in CARE environment:
malpem -h

proot info: pid 13749: terminated with signal 11


Udunna

**Comment by ledigchr** [comment]
You want this to evaluate to `True`.
https://github.com/ledigchr/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/bin/malpem-proot#L19

It seems you changed `myGL=" "` (note the space) rather than `myGL=""`.

**Comment by uanazodo** [comment]
Ah yes. Removed the space and got this error message

WARNING: Didn't find libGL library in /usr/lib/nvid*, offscreen rendering
won't work (only relevant for pdf report)

Command in CARE environment:
malpem -h

proot info: pid 14033: terminated with signal 11

U

**Comment by ledigchr** [comment]
This looks related to this issue https://github.com/ledigchr/MALPEM/issues/2

Have you tried adding `export PROOT_NO_SECCOMP=1` to `bin/malpem-proot`

**Comment by uanazodo** [comment]
Aha!!! It works. Well its running now. 
I uncommented line 17 in bin/malpem_proot which I modified to find libGL.so.1 as follows
myGL=`locate 'libGL.so.1' | egrep '*.so.1$' | egrep ^/usr/lib`

then added export PROOT_NO_SECCOMP=1

U

**Comment by uanazodo** [comment]
My appolgoies for the font format in the original question. I copied and pasted an email I sent which bounced to github and it somehow changed the font in some sections. 

U

**Comment by ledigchr** [comment]
no problem, glad it works!
