### ISSUE TITLE
Cannot access to the download site

### ISSUE THREAD

**Issue by thomaschen83** [ledigchr/MALPEM#5]
I've read some of the paper and found MALPEM being a very competitive software. However, when I tried to install, whether by malpem-install in installer folder or by the .tar file, error showed up as

 Downloading http://www.doc.ic.ac.uk/~cl6311/Material/MALPEM/malpem-1.2.tar.gz to /home/user/malpem-1.2/resource.tar.gz
  Extracting file /home/user/malpem-1.2/resource.tar.gz to /home/user/malpem-1.2
Traceback (most recent call last):
  File "./malpem-install", line 460, in <module>
    [base_dir, num_missing] = install_malpem(prefix=base_dir)
  File "./malpem-install", line 413, in install_malpem
    install_resource(res)
  File "./malpem-install", line 328, in install_resource
    extract_resource(res_file, res.dest)
  File "./malpem-install", line 259, in extract_resource
    ztf = tarfile.open(compressed_file, "r:gz")
  File "/usr/lib/python2.7/tarfile.py", line 1691, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1749, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file

Is there something wrong about the download site, or is it only my PC problem getting into the site?

**Comment by ledigchr** [comment]
There was something wrong with the download site. I have updated the weburl, please check the updated readme file.
This issue is fixed in dfce20da29147f702387980400774a3fd7dfa45a
