### ISSUE TITLE
Mask file does not exist

### ISSUE THREAD

**Issue by rhan93** [ledigchr/MALPEM#7]
Hi,

I am getting the error that "File does not exist (/malpem/atlas/nmm/mri_masked_scaled/a4.nii.gz)". Are these files supposed to be downloaded during installation?

Best,
Runze

Log file:
bin/malpem-proot: line 17: locate: command not found
WARNING: Didn't find libGL library in /usr/lib/nvid*, offscreen rendering won't work (only relevant for pdf report)
Copying file atlas/pincram/limages/full/m100.nii.gz to input directory:
cp atlas/pincram/limages/full/m100.nii.gz bin/../lib/care//rootfs/tmp//input//tmp.zq7ZCzlA52/

Command in CARE environment:
malpem -i /tmp/input/tmp.zq7ZCzlA52/m100.nii.gz -o /tmp/output/tmp.zq7ZCzlA52/ -t 8

--------------------------------------
Input file: /tmp/input/tmp.zq7ZCzlA52/m100.nii.gz
Output directory: /tmp/output/tmp.zq7ZCzlA52/
Field strength: 1.5T
Max. threads: 8
Using input mask:  False
Using input segmentation:  False
Using transformation to initialise MNI alignment:  False
Performing initial bias correction: True
Stopping after brain extraction: False
Perform another N4 bias correction after the brain extraction: True
Create a subdirectory for output: True
Create final pdf report: True
Will clean up once finished: False
--------------------------------------

--- ERROR: File does not exist (/malpem/atlas/nmm/mri_masked_scaled/a4.nii.gz):  ---
Output directory outputDir doesn't exist, creating it
Moving results to output directory: outputDir
Cleaning up input directory: bin/../lib/care//rootfs/tmp//input//tmp.zq7ZCzlA52

**Comment by ledigchr** [comment]
Hi Runze,

Yes, those files should be downloaded during installation. Please refer to the installation guide for a default installation:
https://github.com/ledigchr/MALPEM/blob/master/README.md#installation

Cheers, Christian

**Comment by rhan93** [comment]
Thank you. I didn't realize that one of the packages was not correctly downloaded due to disk space limitation.
